### ISSUE TITLE
java.nio.file.FileSystemNotFoundException: Provider \"gluster\" not installed"

### ISSUE THREAD

**Issue by miaoze612** [semiosis/glusterfs-java-filesystem#15]
I got "java.nio.file.FileSystemNotFoundException: Provider \"gluster\" not installed"".
I followed README.md in the project.

At first, I added the dependency to my maven project. My project provided a servlet interface to read/write my glisters. I can get my .war, but when i put it into tomcat and startup and called the servlet, I got the Exception.

Then, I tried to cd glusterfs-java-filesystem && mvn package shade:shade, I got the jar successfully. The mvn info is :

Replacing /data2/glusterfs-java-filesystem/target/glusterfs-java-filesystem-1.0.5-SNAPSHOT.jar with /data2/glusterfs-java-filesystem/target/glusterfs-java-filesystem-1.0.5-SNAPSHOT-shaded.jar

I found that the jar path was "/data2/glusterfs-java-filesystem/target/", and I set it in CLASSPATH, but stall the same Exception.

Does the any mistake?  Does it need to install libgfapi-jni? 

Thanks.

**Comment by ppapapetrou76** [comment]
@miaoze612 Did you find the solution to your problem? I have the same issue

**Comment by semiosis** [comment]
If you're using the shaded jar then you don't need to add libgfapi-jni since it is included in the shaded jar.  If you are using maven to pull in glusterfs-java-filesystem then maven will also pull in libgfapi-jni automatically.  However, this error indicates that glusterfs-java-filesystem is not being loaded, or that there is some issue with how you are trying to use it and even though glusterfs-java-filesystem is loaded it is not being found.

Can you show me a snippet of the code that produced this exception?

Thank you

**Comment by ppapapetrou76** [comment]
Hi @semiosis 
I'm using maven to pull the dependencies. The generated .war contains the following jars
- libfgapi-all-1.0.4.jar
- gluster-java-filesystem.1.0.4.jar

Here's the code that 
```
fileSystemUri = "gluster://192.128.0.2:datastore/";
 try {
      FileSystem fileSystem = FileSystems.newFileSystem(URI.create(fileSystemUri), null);
      FileStore store = fileSystem.getFileStores().iterator().next();
    } catch (IOException | IllegalArgumentException ex) {
      LOGGER.error("GLUSTER FS FAILED TO INITIALIZE", ex);
    }
```
it fails when trying to create the fileSystem.
The same code outside the .war file works fine. We have a nice integration tests suite that runs against a glusterfs docker container without any problem.

**Comment by semiosis** [comment]
Not sure exactly why that would happen, but I suspect it has to do with the JVM not finding [java.nio.file.spi.FileSystemProvider](https://github.com/semiosis/glusterfs-java-filesystem/blob/master/glusterfs-java-filesystem/src/main/resources/META-INF/services/java.nio.file.spi.FileSystemProvider).  That file causes the JVM to load the filesystem provider and make it available.

**Comment by semiosis** [comment]
This seems relevant: http://stackoverflow.com/questions/7692497/tomcat-wont-load-my-meta-inf-services-javax-servlet-servletcontainerinitializ

HTH

**Comment by ppapapetrou76** [comment]
Hi 
Problem solved like this : 

`FileSystems.newFileSystem(URI.create(fileSystemUri), env, Thread.currentThread().getContextClassLoader());`

I added the ClassLoader as parameter et voila !!!

Thanks a lot for your help

**Comment by semiosis** [comment]
Awesome!  Glad you figured it out.
